# Window configurations
PADDING = 30
WINDOW_WIDTH = 720
WINDOW_HEIGHT = 720
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT
FPS = 60

# Game configurations
ROWS = 10
COLUMNS = 10
CELL_SIZE = 30

# Colors
GRAY = "#1C1C1C"